module.exports = {
  BRONZE_MULTIPLICATOR: 'BRONZE_MULTIPLICATOR',
  SILVER_MULTIPLICATOR: 'SILVER_MULTIPLICATOR',
  GOLD_MULTIPLICATOR: 'GOLD_MULTIPLICATOR',
  FIRST_ATTEMPT: 'FIRST_ATTEMPT',
  FIRST_WON: 'FIRST_WON',
  LUCKY_NUMBER: 'LUCKY_NUMBER'
};
